name: build-lint-test
on:
  push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve envs
        env:
          setupFile: ${{ secrets.ENV }}
        run: mkdir -p .jest && \
          echo "$setupFile" | base64 -d > .jest/setEnvVars.js
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: npm run test

