name: build-lint-test
on:
  push
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Decrypt secret
        run: ./.github/scripts/decrypt_secret.sh
        env:
          ENV_PASSPHRASE: ${{ secrets.ENV_PASSPHRASE }}
      - name: Test printing envs
        run: cat .jest/setEnvVars.js
  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
      - run: npm install
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: npm run test

